test: Mock all cozy-ui files
We do not need to test cozy-ui methods.

To avoid

    SyntaxError: Cannot use import statement outside a module

    > 67 | import { nameToColor } from "cozy-ui/transpiled/react/Avatar/helpers";